"""Exceptions and error handling for pydocgen."""

from pydocgen.errors.exceptions import (
    AuthenticationError,
    BatchError,
    ConcurrencyError,
    ConfigurationError,
    CredentialAlreadyExistsError,
    CredentialError,
    CredentialNotFoundError,
    CredentialStorageError,
    ExitCode,
    FileValidationError,
    FormattingError,
    GenerationError,
    InvalidCredentialError,
    ParseError,
    PipelineExecutionError,
    ProviderError,
    ProviderResponseError,
    ProviderTimeoutError,
    PyDocGenError,
    PydocgenError,
    RateLimitError,
    SourceEditError,
    ValidationError,
)

__all__ = [
    "AuthenticationError",
    "BatchError",
    "ConcurrencyError",
    "ConfigurationError",
    "CredentialAlreadyExistsError",
    "CredentialError",
    "CredentialNotFoundError",
    "CredentialStorageError",
    "ExitCode",
    "FileValidationError",
    "FormattingError",
    "GenerationError",
    "InvalidCredentialError",
    "ParseError",
    "PipelineExecutionError",
    "ProviderError",
    "ProviderResponseError",
    "ProviderTimeoutError",
    "PyDocGenError",
    "PydocgenError",
    "RateLimitError",
    "SourceEditError",
    "ValidationError",
]
